(() => {
  'use strict';
  const TYPES={
    bacteria:{name:'세균',case:'항생제 감수성 폐렴구균 모형',accent:'#ff9f68',unit:'세균 상대량',treatments:[
      {id:'none',name:'치료하지 않음',desc:'비교 기준',target:'없음',effect:0,kind:'none'},
      {id:'wall',name:'세포벽 합성 억제',desc:'분열할 때 새 세포벽을 만드는 과정을 방해',target:'세균의 세포벽 합성',effect:.115,kind:'effective'},
      {id:'protein',name:'세균 단백질 합성 억제',desc:'세균 리보솜의 작용을 방해',target:'세균 리보솜',effect:.086,kind:'effective'},
      {id:'rna',name:'바이러스 RNA 복제 억제',desc:'바이러스에 사용하는 표적을 잘못 선택',target:'바이러스 RNA 중합효소',effect:0,kind:'wrong'}],base:.078,damage:.034,clear:.014,assumption:'앱에서 설정한 항생제 감수성 세균을 가정합니다. 실제 세균은 종류와 내성에 따라 반응이 다릅니다.'},
    virus:{name:'바이러스',case:'코로나바이러스 세포 내 복제 모형',accent:'#72b7ff',unit:'바이러스 상대량',treatments:[
      {id:'none',name:'치료하지 않음',desc:'비교 기준',target:'없음',effect:0,kind:'none'},
      {id:'entry',name:'새로운 세포 침입 억제',desc:'수용체 결합·진입 단계의 성공률을 낮춤',target:'바이러스 진입 과정',effect:.058,kind:'effective'},
      {id:'polymerase',name:'RNA 복제 억제',desc:'새 바이러스 RNA 합성을 방해',target:'바이러스 RNA 중합효소',effect:.102,kind:'effective'},
      {id:'protease',name:'단백질 가공 억제',desc:'복제 단백질이 기능하는 과정을 방해',target:'바이러스 단백질분해효소',effect:.086,kind:'effective'},
      {id:'wall',name:'세균 세포벽 합성 억제',desc:'항생제 표적을 잘못 선택',target:'세균의 세포벽',effect:0,kind:'wrong'}],base:.083,damage:.038,clear:.010,assumption:'하나의 코로나바이러스 복제 원리를 단순화한 모형입니다. 모든 바이러스의 생활사와 치료 표적이 같지는 않습니다.'},
    prion:{name:'프리온',case:'비정상 단백질 구조 전파 모형',accent:'#c28cff',unit:'비정상 단백질 상대량',treatments:[
      {id:'none',name:'개입하지 않음',desc:'비교 기준',target:'없음',effect:0,kind:'none'},
      {id:'support',name:'보조적 관리',desc:'불편과 증상 부담을 낮추는 상황을 표현',target:'증상 부담',effect:0,damageRelief:.22,kind:'support'},
      {id:'conversion',name:'구조 전환 억제 가정',desc:'정상 단백질이 비정상 형태로 바뀌는 속도를 낮춤',target:'비정상 접힘 전환',effect:.054,kind:'hypothesis'},
      {id:'clearance',name:'제거 촉진 가정',desc:'비정상 단백질의 제거율을 높임',target:'비정상 단백질 제거',effect:.043,kind:'hypothesis'},
      {id:'antibiotic',name:'세균 세포벽 합성 억제',desc:'프리온에 없는 표적을 선택',target:'세균의 세포벽',effect:0,kind:'wrong'}],base:.052,damage:.043,clear:.006,assumption:'구조 전환 억제와 제거 촉진은 원리를 탐구하기 위한 가상 가정입니다. CJD 진행을 멈춘다고 입증된 특정 치료법으로 제시하지 않습니다.'}
  };
  const section=document.createElement('section');section.id='treatment-lab';section.innerHTML=`<div class="lab-shell"><header class="lab-head"><div><p class="eyebrow">TREATMENT TARGET LAB</p><h2>어디를 막아야 진행이 달라질까?</h2><p>같은 시작 조건에서 치료하지 않은 경우와 선택한 치료 표적을 나란히 비교합니다. 결과값은 실제 환자 자료가 아닌 교육용 상대지수입니다.</p></div><span class="lab-badge">가상실험 · 진단 및 처방용 아님</span></header>
  <div class="lab-pathogens" role="tablist" aria-label="실험 대상"><button data-lab-type="bacteria" role="tab">세균 <small>· 폐렴구균</small></button><button data-lab-type="virus" role="tab" aria-selected="true">바이러스 <small>· 코로나바이러스</small></button><button data-lab-type="prion" role="tab">프리온 <small>· 단백질 전파</small></button></div>
  <div class="lab-grid"><form class="lab-panel" id="therapyForm"><h3 id="labCase"></h3><p>치료 표적과 적용 시점을 선택하세요.</p><fieldset class="lab-field"><legend>1. 치료 표적</legend><div class="target-list" id="targetList"></div></fieldset><fieldset class="lab-field"><div class="timing-line"><legend>2. 개입 시점</legend><output id="startOutput">20단계</output></div><input type="range" id="startTime" min="10" max="40" step="5" value="20" aria-label="치료 개입 시점"><small>빠르게 적용할수록 앞선 증식·손상을 되돌릴 수 없다는 차이가 보입니다.</small></fieldset><button class="lab-run" type="submit">치료 적용하고 비교하기</button><button class="lab-reset" type="button" id="labReset">조건 초기화</button><p class="lab-assumption" id="labAssumption"></p></form>
  <div class="lab-results"><div class="lab-scene"><div class="lab-chamber"><h4>A · 치료하지 않음</h4><canvas id="controlScene" width="540" height="280"></canvas></div><div class="lab-chamber"><h4>B · 선택한 치료</h4><span class="lab-therapy-flash" id="therapyFlash" hidden>치료 적용</span><canvas id="treatedScene" width="540" height="280"></canvas></div></div><div class="lab-player"><button id="labPlay" type="button">▶ 재생</button><input id="labSeek" type="range" min="0" max="60" step="1" value="0" aria-label="실험 시간"><span id="labTime">0 / 60</span></div><div class="lab-metrics"><div class="lab-metric"><small id="amountLabel">병원성 인자 상대량</small><strong id="amountValue">—</strong><em>치료 없음 대비</em></div><div class="lab-metric"><small>정상 조직 상대지수</small><strong id="healthValue">—</strong><em>100에서 시작</em></div><div class="lab-metric"><small>손상 상대지수</small><strong id="damageValue">—</strong><em>높을수록 손상 큼</em></div></div><div class="lab-chart-wrap"><h4>시간에 따른 병원성 인자 상대량</h4><canvas id="labChart" width="760" height="210" aria-label="치료하지 않은 경우와 선택한 치료의 상대량 비교 그래프"></canvas></div><div class="lab-conclusion" id="labConclusion"><strong>실험 준비</strong><br>치료 표적을 고르고 비교하기를 누르세요.</div><p class="lab-limit" id="labLimit"></p></div></div>
  <div class="lab-table"><table><thead><tr><th>대상</th><th>효과가 나타나는 선택</th><th>효과가 없는 선택</th><th>해석의 핵심</th></tr></thead><tbody><tr><th>세균</th><td>세포벽·세균 리보솜 표적</td><td>바이러스 RNA 표적</td><td>세균 고유 구조를 공격할 수 있음</td></tr><tr><th>바이러스</th><td>진입·RNA 복제·단백질 가공 표적</td><td>세균 세포벽 표적</td><td>숙주세포 안 복제 단계 중 바이러스 표적을 선택</td></tr><tr><th>프리온</th><td>확립된 완치 선택 없음</td><td>항생제</td><td>정상 단백질과 구별되는 안전한 표적 확보가 어려움</td></tr></tbody></table></div><div class="lab-hypothesis"><h3>이 앱으로 확인하는 탐구 질문</h3><p>병원성 인자의 구조와 증식·전파 방식이 다르면, 같은 시점에 개입하더라도 치료 표적에 따라 병원성 인자의 양과 조직 손상 변화는 어떻게 달라지는가?</p></div><p class="lab-status" id="labStatus" aria-live="polite"></p></div>`;
  document.getElementById('compare').before(section);
  const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let type='virus',selected='polymerase',start=20,t=0,playing=false,last=0,animation;
  function treatment(){return TYPES[type].treatments.find(x=>x.id===selected)}
  function simulate(target){const cfg=TYPES[type],tx=target||{effect:0};let burden=8,damage=0,arr=[];for(let i=0;i<=60;i++){const active=i>=start;let suppression=active?(tx.effect||0):0;if(type==='prion'&&tx.id==='clearance'&&active)suppression=tx.effect;const growth=Math.max(-.07,cfg.base-suppression);burden=clamp(burden+(growth*burden*(1-burden/128))-cfg.clear*burden,0.5,125);let injury=cfg.damage*burden*(1-damage/105);if(active&&tx.damageRelief)injury*=1-tx.damageRelief;damage=clamp(damage+injury,0,100);arr.push({burden,damage,health:100-damage})}return arr}
  function targetHTML(){const cfg=TYPES[type];$('targetList').innerHTML=cfg.treatments.map((x,i)=>`<label class="target-choice"><input type="radio" name="target" value="${x.id}" ${x.id===selected?'checked':''}><strong>${x.name}</strong><small>${x.desc}</small></label>`).join('');document.querySelectorAll('input[name=target]').forEach(r=>r.onchange=()=>{selected=r.value;renderResult(false)})}
  function setType(next){type=next;const cfg=TYPES[type];selected=type==='bacteria'?'wall':type==='virus'?'polymerase':'support';section.style.setProperty('--lab-accent',cfg.accent);document.querySelectorAll('[data-lab-type]').forEach(b=>b.setAttribute('aria-selected',b.dataset.labType===type?'true':'false'));$('labCase').textContent=cfg.case;$('labAssumption').textContent='모형 조건 · '+cfg.assumption;$('amountLabel').textContent=cfg.unit;targetHTML();t=0;playing=false;renderResult(false)}
  function message(tx,c,a,b){let head,body;if(tx.kind==='effective'){head='표적이 존재하여 진행 양상이 달라졌습니다.';body=`${tx.target}을 억제한 모형에서 최종 상대량이 ${Math.round(c.burden)}에서 ${Math.round(b.burden)}로 달라졌습니다. 이미 발생한 조직 손상은 즉시 되돌아가지 않으므로 개입 시점도 결과에 영향을 줍니다.`}else if(tx.kind==='wrong'){head='선택한 표적이 이 대상에 없습니다.';body=`${tx.target}은 ${TYPES[type].name}의 증식·전파에 필요한 구조가 아니므로, 이 모형에서는 치료하지 않은 경우와 같은 경로가 나타납니다.`}else if(tx.kind==='support'){head='증상 부담과 원인 단백질은 같은 지표가 아닙니다.';body='보조적 관리를 적용해도 비정상 단백질 상대량은 감소하지 않습니다. 원인 진행을 멈추는 치료와 환자의 불편을 줄이는 관리를 구별해야 합니다.'}else if(tx.kind==='hypothesis'){head='연구 가정에서는 축적 속도가 낮아집니다.';body=`${tx.target}을 가정하면 상대량이 낮아지지만, 이는 확립된 치료 효과가 아닙니다. 실제 치료가 되려면 효과뿐 아니라 정상 단백질에 대한 안전성과 인체 내 전달도 검증해야 합니다.`}else{head='치료하지 않은 비교 기준입니다.';body='병원성 인자의 증가와 이에 따른 조직 손상의 변화를 관찰합니다.'}return `<strong>${head}</strong><br>${body}`}
  function drawParticle(ctx,x,y,r,color,shape){ctx.save();ctx.shadowBlur=12;ctx.shadowColor=color;ctx.fillStyle=color;ctx.strokeStyle='#dffaff';ctx.lineWidth=1;if(shape==='bacteria'){ctx.beginPath();ctx.ellipse(x,y,r*1.3,r*.85,0,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(shape==='virus'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();for(let i=0;i<10;i++){let a=i/10*Math.PI*2;ctx.beginPath();ctx.moveTo(x+Math.cos(a)*r,y+Math.sin(a)*r);ctx.lineTo(x+Math.cos(a)*(r+5),y+Math.sin(a)*(r+5));ctx.stroke()}}else{ctx.beginPath();for(let i=0;i<18;i++){const px=x+(i-9)*r*.28,py=y+Math.sin(i*.9)*r*.55;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.lineWidth=5;ctx.strokeStyle=color;ctx.stroke()}ctx.restore()}
  function drawScene(canvas,data,isTreated){const d=data[Math.round(t)],ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#071724');g.addColorStop(1,'#102c37');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#4aa7af';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,h*.75);for(let x=0;x<=w;x+=15)ctx.lineTo(x,h*.75+Math.sin(x*.04)*5);ctx.stroke();const count=Math.round(3+d.burden/5);for(let i=0;i<count;i++){const seed=Math.sin(i*91.37+type.length*33)*43758.5,x=20+Math.abs(seed%1)*(w-40),y=55+Math.abs(Math.sin(seed*4.2))*125;drawParticle(ctx,x,y,5+(i%4),TYPES[type].accent,type)}const damage=d.damage/100;ctx.fillStyle=`rgba(255,66,92,${damage*.38})`;ctx.fillRect(0,h*.73,w,h*.27);for(let i=0;i<8;i++){ctx.fillStyle=i/8<damage?'#ff657b':'#62d4c8';ctx.fillRect(20+i*64,h-34,47,9)}if(isTreated&&t>=start){ctx.strokeStyle='#d6f4ff';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(0,42);ctx.lineTo(w,42);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#c7ecff';ctx.font='13px system-ui';ctx.fillText('개입 후 · '+treatment().target,15,31)}}
  function drawChart(control,treated){const c=$('labChart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p={l:45,r:15,t:15,b:30};ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8fbfb';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d3dfe1';ctx.lineWidth=1;ctx.font='12px system-ui';ctx.fillStyle='#60757c';for(let v=0;v<=120;v+=30){const y=p.t+(120-v)/120*(h-p.t-p.b);ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(v,p.l-28,y+4)}function series(arr,color,dash=[]){ctx.strokeStyle=color;ctx.lineWidth=3;ctx.setLineDash(dash);ctx.beginPath();arr.forEach((d,i)=>{const x=p.l+i/60*(w-p.l-p.r),y=p.t+(120-d.burden)/120*(h-p.t-p.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.setLineDash([])}series(control,'#71838a',[6,5]);series(treated,TYPES[type].accent);const x=p.l+start/60*(w-p.l-p.r);ctx.strokeStyle='#d94f72';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,p.t);ctx.lineTo(x,h-p.b);ctx.stroke();ctx.fillStyle='#9e3350';ctx.fillText('개입',x+4,p.t+12);ctx.fillStyle='#596d73';ctx.fillText('0',p.l-3,h-10);ctx.fillText('시간 단계 60',w-83,h-10)}
  function renderResult(final=true){const cfg=TYPES[type],tx=treatment(),control=simulate(null),treated=simulate(tx),a=control[Math.round(t)],b=treated[Math.round(t)],endA=control[60],endB=treated[60];drawScene($('controlScene'),control,false);drawScene($('treatedScene'),treated,true);drawChart(control,treated);$('therapyFlash').hidden=t<start;$('amountValue').textContent=Math.round(b.burden)+' / '+Math.round(a.burden);$('healthValue').textContent=Math.round(b.health)+' / '+Math.round(a.health);$('damageValue').textContent=Math.round(b.damage)+' / '+Math.round(a.damage);$('labTime').textContent=Math.round(t)+' / 60';$('labSeek').value=Math.round(t);$('labConclusion').innerHTML=message(tx,endA,a,endB);$('labLimit').textContent=`해석 범위: ${cfg.assumption} 그래프의 수치는 상대적인 교육용 지수이며 실제 약효·용량·회복률·환자 예후를 뜻하지 않습니다.`;if(final)$('labStatus').textContent=`${cfg.name} 실험 결과가 갱신되었습니다. ${tx.name}, ${start}단계 개입 조건입니다.`}
  function run(){t=0;playing=true;$('labPlay').textContent='Ⅱ 일시정지';renderResult(false);cancelAnimationFrame(animation);last=performance.now();const tick=now=>{if(!playing)return;t=Math.min(60,t+(now-last)/220);last=now;renderResult(false);if(t<60)animation=requestAnimationFrame(tick);else{playing=false;$('labPlay').textContent='↺ 다시 재생';renderResult(true)}};animation=requestAnimationFrame(tick)}
  document.querySelectorAll('[data-lab-type]').forEach(b=>b.onclick=()=>setType(b.dataset.labType));$('startTime').oninput=e=>{start=Number(e.target.value);$('startOutput').textContent=start+'단계';renderResult(false)};$('therapyForm').onsubmit=e=>{e.preventDefault();run()};$('labPlay').onclick=()=>{if(t>=60){run();return}playing=!playing;$('labPlay').textContent=playing?'Ⅱ 일시정지':'▶ 계속';if(playing){last=performance.now();const tick=now=>{if(!playing)return;t=Math.min(60,t+(now-last)/220);last=now;renderResult(false);if(t<60)animation=requestAnimationFrame(tick);else{playing=false;$('labPlay').textContent='↺ 다시 재생';renderResult(true)}};animation=requestAnimationFrame(tick)}else cancelAnimationFrame(animation)};$('labSeek').oninput=e=>{playing=false;cancelAnimationFrame(animation);t=Number(e.target.value);$('labPlay').textContent=t>=60?'↺ 다시 재생':'▶ 계속';renderResult(false)};$('labReset').onclick=()=>{start=20;$('startTime').value=20;$('startOutput').textContent='20단계';setType(type)};
  const modelContext=document.modelContext;if(modelContext?.registerTool){try{void Promise.resolve(modelContext.registerTool({name:'run_treatment_target_comparison',title:'치료 표적 비교 실행',description:'세균, 바이러스 또는 프리온에 치료 표적과 개입 시점을 적용하여 교육용 상대지수 결과를 화면에 표시합니다.',inputSchema:{type:'object',properties:{pathogen:{type:'string',enum:['bacteria','virus','prion']},target:{type:'string'},startStep:{type:'integer',minimum:10,maximum:40,multipleOf:5}},required:['pathogen','target','startStep'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!TYPES[input.pathogen])throw new Error('지원하지 않는 대상입니다.');const allowed=TYPES[input.pathogen].treatments.map(x=>x.id);if(!allowed.includes(input.target))throw new Error('선택한 대상에 없는 치료 표적입니다.');type=input.pathogen;selected=input.target;start=input.startStep;setType(type);selected=input.target;targetHTML();$('startTime').value=start;$('startOutput').textContent=start+'단계';renderResult(true);section.scrollIntoView({behavior:'smooth'});const c=simulate(null)[60],r=simulate(treatment())[60];return{pathogen:type,target:selected,startStep:start,untreatedFinalAmount:Math.round(c.burden),treatedFinalAmount:Math.round(r.burden),model:'educational_relative_index'}}}))}catch{}}
  setType('virus');
})();
